import bvdcat from '../../Assets/Images/bvdcat.webp'
import trpin from '../../Assets/Images/tripin.webp'
import vandal from '../../Assets/Images/vandal.webp'
import primate from '../../Assets/Images/primate.webp'
import oakparadise from '../../Assets/Images/oakparadise.webp'
import lostboy from '../../Assets/Images/lostboy.webp'
import artpunk from '../../Assets/Images/artpunk.webp'
import trippineape from '../../Assets/Images/trippineape.webp'
import jikan from '../../Assets/Images/jikan.webp'
import primet from '../../Assets/Images/primet.webp'
import Oak_Paradise from '../../Assets/Images/Oak-Paradise.webp'
import Dumpsters from '../../Assets/Images/Dumpsters.webp'
import Infected_Mob from '../../Assets/Images/Infected_Mob.webp'
import Cets_OnCreck from '../../Assets/Images/Cets_OnCreck.webp'
import Famous from '../../Assets/Images/Famous.webp'
import Sphynx from '../../Assets/Images/Sphynx.webp'


export const featureSlider = [
    {
        id: 'A1',
        img: bvdcat,
        Bvdcat: "Bvdcat",
        name: "BVDCAT #9190",
        title: " 2EDn...fmiA",
        ticket: "Tickets Remaining",
        ticketname: " 142 / 150",
        price: "Price/Ticket",
        tickeprice: "2 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Orange",
        Fur: "Gray Tabby",
        Eyes: "Sus",
        Clothes: "None",
        Head: "Chewy Dad Cap",
        Glasses: "None",
        Mouth: "Cigar"
    },
    {
        id: 'A2',
        img: trpin,
        Bvdcat: "Trippin Ape Tribe",
        name: "Trippin' Ape Tribe #9500",
        title: " 2Xqu...JqCt",
        ticket: "Tickets Remaining",
        ticketname: " 163 / 190",
        price: "Price/Ticket",
        tickeprice: "2 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Watercolor",
        Body: "Body",
        Outfit: "Brown Robe",
        Face: "Gold Grill",
        Eyes: "Holy F_k",
        Hat: "White Bucket"
    },
    {
        id: 'A3',
        img: vandal,
        Bvdcat: "Vandal City",
        name: "Vandal #7316",
        title: "@NFTlittleFroggy",
        ticket: "Tickets Remaining",
        ticketname: " 105 / 150",
        price: "Price/Ticket",
        tickeprice: "2.99 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Mint",
        Clothing: "Pilot Brown",
        Hood: "Cross",
        Head: "Tone II",
        Eyes: "Brown",
        Mouth: "Happy",
        Hair: "Buzz Orange",
        Earrings: "None",
        Eyewear: "None",
        Scarf: "Pink Tie Dye",
        Headwear: "Cowboy",
        Weapon: "Controller",
        Hand: "Hand Wraps Black",
        Rings: "None",
        Wristwear: "None",
        Level: "7"
    },
    {
        id: 'A4',
        img: primate,
        Bvdcat: "Primates",
        name: "Primate #8552",
        title: "@doxxedape",
        ticket: "Tickets Remaining",
        ticketname: " 42 / 50",
        price: "Price/Ticket",
        tickeprice: "8.4 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Body: "Robot",
        Clothing: "Football Pads",
        Eyes: "Pritv",
        Mouth: "Dumbfounded",
        Head: "None",
        Background: "Orange",
    },
    {
        id: 'A5',
        img: oakparadise,
        Bvdcat: "Oak Primates",
        name: "Oak Paradise #1143",
        title: "@Gyf70291007Gyf",
        ticket: "Tickets Remaining",
        ticketname: " 91 / 100",
        price: "Price/Ticket",
        tickeprice: "3.4 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Forest Full Of Wonders",
        Body: "Forest",
        Eyes: "Brick",
        Clothing: "Bark",
        Mask: "Stone"
    },
    {
        id: 'A6',
        img: trippineape,
        Bvdcat: "Trippin Ape Tribe",
        name: "Trippin' Ape Tribe #1065",
        title: "BbwJ...YbQU",
        ticket: "Tickets Remaining",
        ticketname: " 75 / 76",
        price: "Price/Ticket",
        tickeprice: "5.99 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Mint",
        Body: "Drippy Pink",
        Outfit: "Groovy Green",
        Face: "Gold Grill",
        Eyes: "Alert Blue",
        Hat: "Beanie",
    },
    {
        id: 'A7',
        img: lostboy,
        Bvdcat: "Lostboyclub",
        name: "LOST BOY CLUB #2273",
        title: "@skeyloops",
        ticket: "Tickets Remaining",
        ticketname: " 58 / 120",
        price: "Price/Ticket",
        tickeprice: "0.1 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        BACKGROUND: "GRADIENT EMINENCE",
        BODY: "MEDIUM",
        HAIR: "KOREAN MULLET BLOND",
        FACE: "DORK",
        MOUTH: "OPEN",
        OUTFIT: "MUSTARD SLEEVELESS",
        ACCESSORIES: "CLASSIC PERFORATED PIERCING"
    },
    {
        id: 'A8',
        img: artpunk,
        Bvdcat: "Lostboyclub",
        name: "LOST BOY CLUB #2273",
        title: "@skeyloops",
        ticket: "Tickets Remaining",
        ticketname: " 58 / 120",
        price: "Price/Ticket",
        tickeprice: "0.1 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Rank: "1712/10000",
        CryptoPunkrank: "6934/10000",
        CryptoPunktype: "Male",
        CryptoPunkskin: "Mid",
        Paintingstylerank: "83/250",
        Paintingenglishtitle: "Anxiety",
        Paintingoriginaltitle: "Angst",
        Paintingauthor: "Edvard Munch",
        Authornationality: "Norwegian",
        Movement: "Expressionism",
        Paintingtype: "Oil on canvas",
        Paintingyear: "1894",
        Attribute0: "Normal Beard",
        Attribute1: "Mohawk Dark",
        Attribute2: "Eye Patch",
        Numberofattributes: "3",
        RestorationGrade: "Excellent",
    },
    {
        id: 'A9',
        img: jikan,
        Bvdcat: "Jikan",
        name: "Jikan #6304",
        title: "@ggezNFTgains",
        ticket: "Tickets Remaining",
        ticketname: " 224 / 250",
        price: "Price/Ticket",
        tickeprice: "1 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Spring",
        Clothing: "Black Tux",
        Face: "Tone Two",
        Fur: "Red Tribal",
        Necklace: "Teeth",
        Weapon: "Kunai",
        Mouth: "Base",
        Eyes: "Pink Cyborg",
        Earings: "None",
        Headware: "Fedora",
        Eyewear: "Orange Shades",
        Hands: "Base",
        HandJewelry: "Gold Watch",
    },
    {
        id: 'A10',
        img: primet,
        Bvdcat: "Primates",
        name: "Primate #2218",
        title: "@dezuki_",
        ticket: "Tickets Remaining",
        ticketname: " 17 / 50",
        price: "Price/Ticket",
        tickeprice: "8.99 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Body: "Skeleton",
        Clothing: "Studded Punk Jacket",
        Eyes: "Bone Mask",
        Mouth: "Excited",
        Head: "None",
        Background: "Orange",
    },
    {
        id: 'A11',
        img: Oak_Paradise,
        Bvdcat: "Oak Paradise",
        name: "Oak Paradise #4965",
        title: "@Gyf70291007Gyf",
        ticket: "Tickets Remaining",
        ticketname: " 76 / 110",
        price: "Price/Ticket",
        tickeprice: "3 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Cave",
        Body: "Undead",
        Eyes: "Circles",
        Clothing: "Bone Tunic",
        Mask: "Dragon",

    },
    {
        id: 'A12',
        img: Dumpsters,
        Bvdcat: "Dumpster",
        name: "Degen Trash Dumpster: #1972",
        title: "@yoyoyoloNFTs",
        ticket: "Tickets Remaining",
        ticketname: " 158 / 170",
        price: "Price/Ticket",
        tickeprice: "1 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Dumpster: "Brown",
    },
    {
        id: 'A13',
        img: Infected_Mob,
        Bvdcat: "Infected Mob",
        name: "Infected Mob #4410",
        title: "@ba92358",
        ticket: "Tickets Remaining",
        ticketname: " 355 / 460",
        price: "Price/Ticket",
        tickeprice: "0.5 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Lagoon Blue",
        Body: "Canned Swiss Guard",
        Skin: "Worm Infested",
        Eyes: "3D Perspective",
        Headwear: "Happy Birthday",
    },
    {
        id: 'A14',
        img: Cets_OnCreck,
        Bvdcat: "Cets On Creck",
        name: "Cet #6085",
        title: "@haitham_127",
        ticket: "Tickets Remaining",
        ticketname: " 222 / 440",
        price: "Price/Ticket",
        tickeprice: "3 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Orange",
        Skin: "peblo",
        Clothing: "Naked",
        Mouth: "Grin",
        Eye: "Battle eye",
        Headgear: "No Headgear",

    },
    {
        id: 'A15',
        img: Famous,
        Bvdcat: "Famous Fox Federation",
        name: "Fox #5521",
        title: "@aziamanuel",
        ticket: "Tickets Remaining",
        ticketname: " 335 / 400",
        price: "Price/Ticket",
        tickeprice: "3 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Alabaster",
        Outfit: "Scarf Red",
        Skin: "Natural",
        Mouth: "Grin",
        Head: "Cap Blue",
        Eyes: "Mutated",

    },
    {
        id: 'A16',
        img: Sphynx,
        Bvdcat: "Sphynx Underground Society",
        name: "Sphynx #7515",
        title: "@SNft1970",
        ticket: "Tickets Remaining",
        ticketname: " 32 / 65",
        price: "Price/Ticket",
        tickeprice: "0.3 DUST",
        view: "View Raffle",
        second: "Ends in 9 hrs 23 mins 9s",
        Solscan: "View on Solscan",
        Background: "Off White",
        Snout: "Ground",
        Body: "Turquoise",
        Eyes: "X Pink",
        Clothing: "White Tank Top",
        Head: "Red Hair",
        Region: "Canada",
        Role: "Role",
        Mouth: "Bored",

    },
];