import trpin from "../../Assets/Images/tripin.webp";
import vandal from "../../Assets/Images/vandal.webp";
import primate from "../../Assets/Images/primate.webp";
import oakparadise from "../../Assets/Images/oakparadise.webp";
import trippineape from "../../Assets/Images/trippineape.webp";
import lostboy from "../../Assets/Images/lostboy.webp";
import artpunk from "../../Assets/Images/artpunk.webp";
import bvdcat from "../../Assets/Images/bvdcat.webp";

export const FeatureSlider = [
   {
      id: 1,
      img: bvdcat,
      Bvdcat: "Bvdcat",
      name: "BVDCAT #9190",
      title: " 2EDn...fmiA",
      ticket: "Tickets Remaining",
      ticketname: " 142 / 150",
      price: "Price/Ticket",
      tickeprice: "2 DUST",
      view: "View Raffle",
      second: "Ends in 9 hrs 23 mins 9s",
      Solscan: "View on Solscan",
      Background: "Orange",
      Fur: "Gray Tabby",
      Eyes: "Sus",
      Clothes: "None",
      Head: "Chewy Dad Cap",
      Glasses: "None",
      Mouth: "Cigar"
   },
   {
      id: 2,
      img: trpin,
      Bvdcat: "Trippin Ape Tribe",
      name: "Trippin' Ape Tribe #9500",
      title: " 2Xqu...JqCt",
      ticket: "Tickets Remaining",
      ticketname: " 163 / 190",
      price: "Price/Ticket",
      tickeprice: "2 DUST",
      view: "View Raffle",
      second: "Ends in 9 hrs 23 mins 9s",
      Solscan: "View on Solscan",
      Background: "Watercolor",
      Body: "Body",
      Outfit: "Brown Robe",
      Face: "Gold Grill",
      Eyes: "Holy F_k",
      Hat: "White Bucket"
   },
   {
      id: 3,
      img: vandal,
      Bvdcat: "Vandal City",
      name: "Vandal #7316",
      title: "@NFTlittleFroggy",
      ticket: "Tickets Remaining",
      ticketname: " 105 / 150",
      price: "Price/Ticket",
      tickeprice: "2.99 DUST",
      view: "View Raffle",
      second: "Ends in 9 hrs 23 mins 9s",
      Solscan: "View on Solscan",
      Background: "Background",
      Clothing: "Clothing",
      Hood: "Cross",
      Head: "Tone II",
      Eyes: "Brown",
      Mouth: "Happy",
      Hair: "Buzz Orange",
      Earrings: "None",
      Eyewear: "None",
      Scarf: "Pink Tie Dye",
      Headwear: "Cowboy",
      Weapon: "Controller",
      Hand: "Hand Wraps Black",
      Rings: "None",
      Wristwear: "None",
      Level: "7"
   },
   {
      id: 4,
      img: primate,
      Bvdcat: "Primates",
      name: "Primate #8552",
      title: "@doxxedape",
      ticket: "Tickets Remaining",
      ticketname: " 42 / 50",
      price: "Price/Ticket",
      tickeprice: "8.4 DUST",
      view: "View Raffle",
      second: "Ends in 9 hrs 23 mins 9s",
      Solscan: "View on Solscan",
      Body: "Robot",
      Clothing: "Football Pads",
      Eyes: "Pritv",
      Mouth: "Dumbfounded",
      Head: "None",
      Background: "Orange",

   },
   {
      id: 5,
      img: oakparadise,
      Bvdcat: "Oak Primates",
      name: "Oak Paradise #1143",
      title: "@Gyf70291007Gyf",
      ticket: "Tickets Remaining",
      ticketname: " 91 / 100",
      price: "Price/Ticket",
      tickeprice: "3.4 DUST",
      view: "View Raffle",
      second: "Ends in 9 hrs 23 mins 9s",
      Solscan: "View on Solscan",
      Background: "Forest Full Of Wonders",
      Body: "Forest",
      Eyes: "Brick",
      Clothing: "Bark",
      Mask: "Stone"
   },
   {
      id: 6,
      img: trippineape,
      Bvdcat: "Trippin Ape Tribe",
      name: "Trippin' Ape Tribe #1065",
      title: "BbwJ...YbQU",
      ticket: "Tickets Remaining",
      ticketname: " 75 / 76",
      price: "Price/Ticket",
      tickeprice: "5.99 DUST",
      view: "View Raffle",
      second: "Ends in 9 hrs 23 mins 9s",
      Solscan: "View on Solscan",
      Background: "Mint",
      Body: "Drippy Pink",
      Outfit: "Groovy Green",
      Face: "Gold Grill",
      Eyes: "Alert Blue",
      Hat: "Beanie",
   },
   {
      id: 7,
      img: lostboy,
      Bvdcat: "Lostboyclub",
      name: "LOST BOY CLUB #2273",
      title: "@skeyloops",
      ticket: "Tickets Remaining",
      ticketname: " 58 / 120",
      price: "Price/Ticket",
      tickeprice: "0.1 DUST",
      view: "View Raffle",
      second: "Ends in 9 hrs 23 mins 9s",
      Solscan: "View on Solscan",
      BACKGROUND: "GRADIENT EMINENCE",
      BODY: "MEDIUM",
      HAIR: "KOREAN MULLET BLOND",
      FACE: "DORK",
      MOUTH: "OPEN",
      OUTFIT: "MUSTARD SLEEVELESS",
      ACCESSORIES: "CLASSIC PERFORATED PIERCING"
   },
   {
      id: 8,
      img: artpunk,
      Bvdcat: "Lostboyclub",
      name: "LOST BOY CLUB #2273",
      title: "@skeyloops",
      ticket: "Tickets Remaining",
      ticketname: " 58 / 120",
      price: "Price/Ticket",
      tickeprice: "0.1 DUST",
      view: "View Raffle",
      second: "Ends in 9 hrs 23 mins 9s",
      Solscan: "View on Solscan",
      Rank: "1712/10000",
      CryptoPunkrank: "6934/10000",
      CryptoPunktype: "Male",
      CryptoPunkskin: "Mid",
      Paintingstylerank: "83/250",
      Paintingenglishtitle: "Anxiety",
      Paintingoriginaltitle: "Angst",
      Paintingauthor: "Edvard Munch",
      Authornationality: "Norwegian",
      Movement: "Expressionism",
      Paintingtype: "Oil on canvas",
      Paintingyear: "1894",
      Attribute0: "Normal Beard",
      Attribute1: "Mohawk Dark",
      Attribute2: "Eye Patch",
      Numberofattributes: "3",
      RestorationGrade: "Excellent",






   }
];